export const partners = [
  { name: "Cisco", logo: "/logos/cisco.webp", link: "https://www.cisco.com" },
  { name: "Huawei", logo: "/logos/huawei.webp", link: "https://www.huawei.com" },
  { name: "GDI", logo: "/logos/GDI.webp", link: "https://www.gdi.org" },
  { name: "Konza", logo: "/logos/Konza.webp", link: "https://konza.go.ke" },
  { name: "KNCCI", logo: "/logos/KNCCI.webp", link: "https://www.kncci.org" },
  { name: "DC Donates", logo: "/logos/DC_Donates_logo_regular.webp", link: "https://www.datacamp.com/donates" },
  { name: "ICT", logo: "/logos/ict.webp", link: "https://ict.go.ke" },
  { name: "NGOsource", logo: "/logos/ngosource.webp", link: "https://www.ngosource.org" },
  { name: "Mastercard Foundation", logo: "/logos/mastercard-foundation.webp", link: "https://mastercardfoundation.org" },
  { name: "Liquid Intelligent Technologies", logo: "/logos/liquid-intelligent-technologies.webp", link: "https://www.liquid.tech" },
  { name: "National Museums of Kenya", logo: "/logos/national-museums.webp", link: "https://museums.or.ke" },
  { name: "Mombasa County", logo: "/logos/mombasa-county.webp", link: "https://mombasa.go.ke" },
  { name: "Absa", logo: "/logos/absa.webp", link: "https://www.absabank.co.ke" },
  { name: "Conrad Hilton Foundation", logo: "/logos/conradhiltonfoundation.webp", link: "https://www.hiltonfoundation.org" },
];
