export const partners = [
  { name: "Cisco", logo: "/partners/cisco.webp", link: "https://www.cisco.com" },
  { name: "Huawei", logo: "/partners/huawei.webp", link: "https://www.huawei.com" },
  { name: "GDI", logo: "/partners/GDI.webp", link: "https://www.gdi.org" },
  { name: "Konza", logo: "/partners/Konza.webp", link: "https://konza.go.ke" },
  { name: "KNCCI", logo: "/partners/KNCCI.webp", link: "https://www.kncci.org" },
  { name: "DC Donates", logo: "/partners/DC_Donates_logo_regular.webp", link: "https://www.datacamp.com/donates" },
  { name: "ICT", logo: "/partners/ict.webp", link: "https://ict.go.ke" },
  { name: "NGOsource", logo: "/partners/ngosource.webp", link: "https://www.ngosource.org" },
  { name: "Mastercard Foundation", logo: "/partners/mastercard-foundation.webp", link: "https://mastercardfoundation.org" },
  { name: "Liquid Intelligent Technologies", logo: "/partners/liquid.webp", link: "https://www.liquid.tech" },
  { name: "National Museums of Kenya", logo: "/partners/national-museums.webp", link: "https://museums.or.ke" },
  { name: "Mombasa County", logo: "/partners/county.webp", link: "https://mombasa.go.ke" },
  { name: "Absa", logo: "/partners/absa.webp", link: "https://www.absabank.co.ke" },
  { name: "Conrad Hilton Foundation", logo: "/partners/conradhiltonfoundation.webp", link: "https://www.hiltonfoundation.org" },
];
